sudo: false

language: bash
services: docker

env:
  global:
    - GCG_VERSION=v1.14.3

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: azavea/docker-github-changelog-generator
      branch: master
