#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
"Usage: $(basename "$0")
Test container images built from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else

        docker run --rm -it \
         "quay.io/azavea/github-changelog-generator:${GCG_VERSION}" \
         --help | grep "Usage: github_changelog_generator"

    fi
fi